export type CompetitorTier = 'Enterprise' | 'Mid-Market' | 'Solo Mobile' | 'Aggregator';

export interface CompetitorFeatureScore {
  category: string;
  airbook: number; // 1 to 5
  competitor: number; // 1 to 5
  comparisonNote: string;
}

export interface CompetitorProfile {
  id: string;
  name: string;
  slug: string;
  tagline: string;
  tier: CompetitorTier;
  logoInitial: string;
  logoUrl?: string;
  accentColor: string;
  pricingModel: {
    basePrice: string;
    processingRate: string;
    hiddenFeesNote: string;
    lockInPeriod: string;
  };
  overview: string;
  strengths: string[];
  weaknesses: string[];
  darkPatterns: string[];
  airbookMoatAdvantage: string;
  featureScores: CompetitorFeatureScore[];
}

export const COMPETITORS: CompetitorProfile[] = [
  {
    id: 'fresha',
    name: 'Fresha',
    slug: 'fresha',
    tagline: 'Global salon marketplace with high client capture fees',
    tier: 'Aggregator',
    logoInitial: 'F',
    logoUrl: '/images/competitors/fresha.png',
    accentColor: '#10B981',
    pricingModel: {
      basePrice: '$0 / mo ("Free" Software Hook)',
      processingRate: '2.19% + 20¢ per transaction',
      hiddenFeesNote: '20% + VAT on every first-time client discovered via marketplace; 1.29% + 20¢ on recurring clients.',
      lockInPeriod: 'No contract, but heavy client lock-in via marketplace ownership',
    },
    overview: 'Fresha offers "free" booking software to salon operators, but monetizes by taxing 20% on every new client that finds the salon through their marketplace directory. They retain direct marketing relationships with the salon’s end clients.',
    strengths: [
      'Zero upfront monthly subscription cost attracts cash-strapped solo artists',
      'High consumer brand awareness through global consumer marketplace',
      'Decent basic POS and appointment calendar functionality',
    ],
    weaknesses: [
      'Heavy 20% commission penalty on new client acquisition',
      'Client hijacking: Fresha markets competing salons to your existing clients',
      'No custom domain white-labeling (must use fresha.com links)',
      'Legacy password authentication with frequent credential resets',
    ],
    darkPatterns: [
      'Marketplace Client Hijack: Fresha collects client emails and sends marketing emails recommending nearby competitor salons.',
      'Hidden Processing Markups: Processing fee surcharges apply even when clients book directly through Instagram.',
    ],
    airbookMoatAdvantage: 'AirBook charges 0% client penalty fees, guarantees total client database ownership with zero competitor cross-promotion, provides white-label custom domain storefronts, and uses 100% passwordless passkey security.',
    featureScores: [
      { category: 'Booking Engine UX', airbook: 5, competitor: 4, comparisonNote: 'AirBook offers ergonomic bottom-sheet drawer with 1-tap booking vs. multi-step modal.' },
      { category: 'Fee Transparency', airbook: 5, competitor: 1, comparisonNote: 'AirBook has 0% marketplace capture tax vs. Fresha’s 20% first-time client penalty.' },
      { category: 'White-Label & Domain', airbook: 5, competitor: 1, comparisonNote: 'AirBook supports custom CNAME domains vs. mandatory fresha.com URLs.' },
      { category: 'Security & Auth', airbook: 5, competitor: 2, comparisonNote: 'AirBook is 100% passwordless (Passkeys/TouchID) vs. legacy email/password.' },
      { category: 'POS Terminal Hardware', airbook: 5, competitor: 3, comparisonNote: 'AirBook pairs directly with Stripe Terminal WisePad 3.' },
      { category: 'Multi-Language i18n', airbook: 5, competitor: 3, comparisonNote: 'AirBook natively supports 4 languages (EN, ES, DE, FR) across entire app.' },
    ],
  },
  {
    id: 'mindbody',
    name: 'Mindbody',
    slug: 'mindbody',
    tagline: 'Legacy fitness & enterprise wellness booking conglomerate',
    tier: 'Enterprise',
    logoInitial: 'M',
    logoUrl: '/images/competitors/mindbody.png',
    accentColor: '#F97316',
    pricingModel: {
      basePrice: '$139 – $699 / mo',
      processingRate: '2.75% – 3.5% + monthly gateway fee',
      hiddenFeesNote: 'Mandatory onboarding/training fees ($300–$1,000); paid add-ons for SMS, dynamic pricing, and branded apps.',
      lockInPeriod: 'Strict 12-month to 36-month locked annual contracts with steep cancellation penalties',
    },
    overview: 'Mindbody is the traditional heavyweight in the gym, yoga, and luxury spa space. It carries massive feature bloat, 15+ years of legacy technical debt, expensive multi-tier pricing, and aggressive enterprise sales reps.',
    strengths: [
      'Comprehensive reporting and complex class scheduling for large health clubs',
      'Established enterprise brand in fitness studios',
      'Deep integration with gym hardware access turnstiles',
    ],
    weaknesses: [
      'Extremely high price point ($139–$699/mo) out of reach for independent salons',
      'Slow, outdated, clunky UI built on legacy codebase with long load times',
      'Locked 1-year contracts with aggressive autorenewal terms',
      'Poor mobile experience requiring separate heavy app downloads',
    ],
    darkPatterns: [
      'Contract Trap: Auto-renews multi-year agreements with difficult certified mail cancellation requirements.',
      'Add-On Inflation: Basic tier lacks fundamental features like 2-way SMS, forcing expensive upgrades.',
    ],
    airbookMoatAdvantage: 'AirBook is lightweight, sub-second fast, starts with a generous free solo tier, requires zero long-term contract lock-ins, and delivers modern consumer-grade UX.',
    featureScores: [
      { category: 'Booking Engine UX', airbook: 5, competitor: 2, comparisonNote: 'AirBook loads in <200ms vs. Mindbody’s heavy 4-second iframe widgets.' },
      { category: 'Fee Transparency', airbook: 5, competitor: 1, comparisonNote: 'AirBook has transparent monthly pricing vs. Mindbody hidden setup fees & contracts.' },
      { category: 'White-Label & Domain', airbook: 5, competitor: 3, comparisonNote: 'AirBook provides instant DNS CNAME setup vs. expensive custom app build fees.' },
      { category: 'Security & Auth', airbook: 5, competitor: 2, comparisonNote: 'AirBook zero-password architecture vs. legacy credentials.' },
      { category: 'POS Terminal Hardware', airbook: 5, competitor: 4, comparisonNote: 'AirBook offers modern wireless Stripe POS vs. proprietary hardware locks.' },
      { category: 'Multi-Language i18n', airbook: 5, competitor: 2, comparisonNote: 'AirBook seamless 4-language i18n vs. fragmented multi-region portals.' },
    ],
  },
  {
    id: 'vagaro',
    name: 'Vagaro',
    slug: 'vagaro',
    tagline: 'Feature-heavy salon platform with pervasive micro-fee add-ons',
    tier: 'Mid-Market',
    logoInitial: 'V',
    logoUrl: '/images/competitors/vagaro.svg',
    accentColor: '#EF4444',
    pricingModel: {
      basePrice: '$30 / mo (1 staff) + $10 / mo per extra staff (up to 7+)',
      processingRate: '2.2% – 2.75% + 15¢',
      hiddenFeesNote: '$10/mo for website builder, $10/mo for custom forms, $10/mo for text marketing, $10/mo for online shopping cart.',
      lockInPeriod: 'Month-to-month, but modular add-on fees balloon bills to $120+/mo',
    },
    overview: 'Vagaro targets independent salons with an accessible $30/mo entry price, but gates essential tools behind dozens of $10/mo add-ons. The interface is visually dated and cluttered with legacy dropdowns.',
    strengths: [
      'Low initial base entry price ($30/mo)',
      'Extensive breadth of niche features (payroll, forms, live streaming)',
      'Large merchant user base in North America',
    ],
    weaknesses: [
      'Nickel-and-diming model: actual cost balloons to $100+/mo with necessary add-ons',
      'Cluttered, non-intuitive UI with overwhelming legacy navigation',
      'Unreliable mobile app performance with frequent crashes',
      'Consumer marketplace directory promotes competitors to your clients',
    ],
    darkPatterns: [
      'Micro-Billing Creep: Basic features like automated intake forms and SMS reminders require separate monthly subscriptions.',
    ],
    airbookMoatAdvantage: 'AirBook includes all core features (intake forms, eSign waivers, staff shifts, Google review automation) in unified, transparent tiers without micro-billing.',
    featureScores: [
      { category: 'Booking Engine UX', airbook: 5, competitor: 3, comparisonNote: 'AirBook has clean tactile floating physics vs. Vagaro’s cluttered legacy forms.' },
      { category: 'Fee Transparency', airbook: 5, competitor: 2, comparisonNote: 'AirBook has zero surprise add-ons vs. Vagaro’s $10/mo add-on maze.' },
      { category: 'White-Label & Domain', airbook: 5, competitor: 2, comparisonNote: 'AirBook includes CNAME white-labeling vs. Vagaro-branded portals.' },
      { category: 'Security & Auth', airbook: 5, competitor: 2, comparisonNote: 'AirBook passkeys vs. standard password database.' },
      { category: 'POS Terminal Hardware', airbook: 5, competitor: 3, comparisonNote: 'AirBook Stripe Terminal integration vs. proprietary card swiper.' },
      { category: 'Multi-Language i18n', airbook: 5, competitor: 2, comparisonNote: 'AirBook native 4-language support vs. English-centric design.' },
    ],
  },
  {
    id: 'boulevard',
    name: 'Boulevard',
    slug: 'boulevard',
    tagline: 'High-end aesthetic & luxury salon management platform',
    tier: 'Enterprise',
    logoInitial: 'B',
    logoUrl: '/images/competitors/boulevard.png',
    accentColor: '#6366F1',
    pricingModel: {
      basePrice: '$175 – $450+ / mo',
      processingRate: 'Custom interchange-plus or 2.6% + 10¢',
      hiddenFeesNote: 'High minimum platform commitment; custom hardware costs ($400+ per terminal).',
      lockInPeriod: 'Annual agreements with custom enterprise onboarding fees',
    },
    overview: 'Boulevard is a premium, beautifully designed salon management platform tailored specifically for high-end luxury salons and medical spas with large staff rosters and high ticket sizes.',
    strengths: [
      'Sleek, modern user interface compared to legacy incumbents',
      'Precision scheduling algorithm optimizing appointment stacking',
      'Strong custom POS hardware (Boulevard Duo reader)',
    ],
    weaknesses: [
      'Prohibitively expensive ($175+/mo base) excluding solo and boutique salons',
      'Lengthy enterprise sales onboarding process with required sales calls',
      'Limited international localization outside North America',
      'Complex configuration overhead for independent artists',
    ],
    darkPatterns: [
      'Gated Pricing: Refuses to publish transparent pricing publicly, forcing mandatory sales demos.',
    ],
    airbookMoatAdvantage: 'AirBook delivers the same ultra-luxury aesthetic and tactile craftsmanship as Boulevard, but with instant self-serve onboarding, a free starter tier, and global 4-language i18n.',
    featureScores: [
      { category: 'Booking Engine UX', airbook: 5, competitor: 5, comparisonNote: 'Both offer top-tier luxury UX; AirBook adds mobile bottom-sheet ergonomics.' },
      { category: 'Fee Transparency', airbook: 5, competitor: 2, comparisonNote: 'AirBook has 100% transparent pricing vs. Boulevard’s gated sales calls.' },
      { category: 'White-Label & Domain', airbook: 5, competitor: 4, comparisonNote: 'Both support white-labeling; AirBook provides 1-click automated DNS check.' },
      { category: 'Security & Auth', airbook: 5, competitor: 3, comparisonNote: 'AirBook 100% passwordless passkeys vs. SSO/password combo.' },
      { category: 'POS Terminal Hardware', airbook: 5, competitor: 5, comparisonNote: 'AirBook uses open Stripe Terminal vs. proprietary Boulevard Duo hardware.' },
      { category: 'Multi-Language i18n', airbook: 5, competitor: 2, comparisonNote: 'AirBook 4-language native support vs. US-only focus.' },
    ],
  },
  {
    id: 'square-appointments',
    name: 'Square Appointments',
    slug: 'square-appointments',
    tagline: 'Generalist retail POS extended with basic appointment scheduling',
    tier: 'Mid-Market',
    logoInitial: 'S',
    logoUrl: '/images/competitors/square.svg',
    accentColor: '#3B82F6',
    pricingModel: {
      basePrice: '$0 (Solo) / $29 / $69 / mo',
      processingRate: '2.6% + 10¢ (in-person) / 2.9% + 30¢ (online)',
      hiddenFeesNote: 'Square ecosystem lock-in; SMS reminders capped on free tier.',
      lockInPeriod: 'Month-to-month',
    },
    overview: 'Square Appointments is a booking extension layered on top of Square’s massive retail payment ecosystem. While it benefits from Square hardware, its salon-specific workflows (formulas, chair shifts, eSign waivers) are shallow.',
    strengths: [
      'Seamless integration with Square Register and Square Terminal hardware',
      'Free starter tier for solo practitioners',
      'Solid financial ecosystem with Square checking and business loans',
    ],
    weaknesses: [
      'Generic retail architecture lacks deep beauty/wellness workflows (color formulas, HIPAA logs, liability waivers)',
      'Booking storefronts look like generic Square retail stores',
      'No custom CNAME domain support (requires square.site URLs)',
      'Weak multi-staff commission calculations for booth renters',
    ],
    darkPatterns: [
      'Ecosystem Trap: Difficult to export customer card tokens if migrating away from Square processing.',
    ],
    airbookMoatAdvantage: 'AirBook is purpose-built for beauty and wellness with client formulas, eSign waivers, chair allocation, candid photography DAM, and bespoke custom domain branding.',
    featureScores: [
      { category: 'Booking Engine UX', airbook: 5, competitor: 3, comparisonNote: 'AirBook bespoke luxury booking flow vs. Square generic checkout look.' },
      { category: 'Fee Transparency', airbook: 5, competitor: 4, comparisonNote: 'Both have clear pricing; AirBook includes beauty tools in core tiers.' },
      { category: 'White-Label & Domain', airbook: 5, competitor: 2, comparisonNote: 'AirBook custom CNAME domain vs. mandatory square.site domain.' },
      { category: 'Security & Auth', airbook: 5, competitor: 3, comparisonNote: 'AirBook passkeys vs. standard Square OTP/password auth.' },
      { category: 'POS Terminal Hardware', airbook: 5, competitor: 5, comparisonNote: 'Both offer excellent hardware; AirBook pairs with Stripe Terminal.' },
      { category: 'Multi-Language i18n', airbook: 5, competitor: 3, comparisonNote: 'AirBook 4-language localized UI vs. standard Square translations.' },
    ],
  },
  {
    id: 'glossgenius',
    name: 'GlossGenius',
    slug: 'glossgenius',
    tagline: 'Mobile-first booking app popular among independent US hairstylists',
    tier: 'Solo Mobile',
    logoInitial: 'G',
    logoUrl: '/images/competitors/glossgenius.jpg',
    accentColor: '#EC4899',
    pricingModel: {
      basePrice: '$24 / mo (Standard) / $48 / mo (Gold)',
      processingRate: '2.6% flat rate (no per-transaction fee)',
      hiddenFeesNote: 'Flat rate processing has built-in margin; limited advanced reporting on standard tier.',
      lockInPeriod: 'Month-to-month',
    },
    overview: 'GlossGenius has achieved strong organic adoption among solo US hair stylists through chic marketing, custom card reader designs (gold/marble), and a clean mobile app interface.',
    strengths: [
      'Attractive mobile app design tailored for solo stylists and aesthetic pros',
      'Simple 2.6% flat payment processing rate without per-transaction cent fees',
      'Aesthetic social media marketing collateral generation',
    ],
    weaknesses: [
      'Weak multi-chair, multi-location, and franchise operational capabilities',
      'Limited international support (US only, no European payment methods or multi-currency)',
      'Basic calendar grid lacks advanced multi-staff drag-and-drop flexibility on desktop',
      'No passwordless biometric authentication',
    ],
    darkPatterns: [
      'Feature Gating: Client review automation and automated text campaigns locked behind $48/mo Gold tier.',
    ],
    airbookMoatAdvantage: 'AirBook matches GlossGenius’s mobile beauty aesthetic while delivering true multi-location franchise power, web-first desktop calendar grid, global 4-language i18n, and biometric passkeys.',
    featureScores: [
      { category: 'Booking Engine UX', airbook: 5, competitor: 4, comparisonNote: 'AirBook has fluid responsive web app vs. GlossGenius mobile-only focus.' },
      { category: 'Fee Transparency', airbook: 5, competitor: 4, comparisonNote: 'Both offer flat rates; AirBook supports multi-currency Stripe Connect.' },
      { category: 'White-Label & Domain', airbook: 5, competitor: 3, comparisonNote: 'AirBook true CNAME white-label vs. glossgenius.com custom subdomains.' },
      { category: 'Security & Auth', airbook: 5, competitor: 2, comparisonNote: 'AirBook passkeys vs. phone OTP.' },
      { category: 'POS Terminal Hardware', airbook: 5, competitor: 4, comparisonNote: 'AirBook Stripe WisePad 3 vs. GlossGenius custom Bluetooth reader.' },
      { category: 'Multi-Language i18n', airbook: 5, competitor: 1, comparisonNote: 'AirBook 4 languages vs. GlossGenius US-only English.' },
    ],
  },
  {
    id: 'booksy',
    name: 'Booksy',
    slug: 'booksy',
    tagline: 'Barbershop-focused booking directory with marketplace search',
    tier: 'Aggregator',
    logoInitial: 'B',
    logoUrl: '/images/competitors/booksy.png',
    accentColor: '#0EA5E9',
    pricingModel: {
      basePrice: '$29.99 / mo + $20 / mo per additional staff',
      processingRate: '2.49% + 20¢',
      hiddenFeesNote: 'Booksy Boost marketplace marketing commission (up to 50% of first appointment from new clients).',
      lockInPeriod: 'Month-to-month',
    },
    overview: 'Booksy is widely used in the urban barbering community. Like Fresha, it operates a consumer marketplace (Booksy Boost) that takes substantial cuts from newly acquired client bookings.',
    strengths: [
      'High brand penetration in barbershops and men’s grooming studios',
      'Walk-in queue manager and waitlist integration',
      'Client review aggregation',
    ],
    weaknesses: [
      'Aggressive Booksy Boost commission (takes up to 50% of 1st service value)',
      'UI is heavily dated and cluttered with marketing banners',
      'Client poaching: marketplace surfaces nearby barbers to your customers',
      'Sub-par custom branding options for luxury spas and aesthetic clinics',
    ],
    darkPatterns: [
      'Booksy Boost Commission Trap: Automatically opts operators into 30%-50% first-booking commissions on marketplace bookings.',
    ],
    airbookMoatAdvantage: 'AirBook protects salon operators with 0% marketplace commission traps, bespoke luxury branding, and zero competitor cross-selling.',
    featureScores: [
      { category: 'Booking Engine UX', airbook: 5, competitor: 3, comparisonNote: 'AirBook tactile drawer vs. Booksy app-install nag screens.' },
      { category: 'Fee Transparency', airbook: 5, competitor: 1, comparisonNote: 'AirBook 0% penalty vs. Booksy Boost up to 50% first-booking tax.' },
      { category: 'White-Label & Domain', airbook: 5, competitor: 1, comparisonNote: 'AirBook white-label vs. mandatory Booksy marketplace branding.' },
      { category: 'Security & Auth', airbook: 5, competitor: 2, comparisonNote: 'AirBook passkeys vs. phone OTP.' },
      { category: 'POS Terminal Hardware', airbook: 5, competitor: 3, comparisonNote: 'AirBook Stripe Terminal POS vs. basic card reader.' },
      { category: 'Multi-Language i18n', airbook: 5, competitor: 3, comparisonNote: 'AirBook 4-language localized architecture vs. basic app strings.' },
    ],
  },
  {
    id: 'mangomint',
    name: 'Mangomint',
    slug: 'mangomint',
    tagline: 'High-end automated booking software for large salons & spas',
    tier: 'Enterprise',
    logoInitial: 'M',
    logoUrl: '/images/competitors/mangomint.png',
    accentColor: '#14B8A6',
    pricingModel: {
      basePrice: '$165 / mo (up to 10 staff) / $245 / mo (up to 20 staff) / $375+ / mo',
      processingRate: '2.45% – 2.6% + 10¢',
      hiddenFeesNote: '$30/mo for two-way texting; expensive base tier.',
      lockInPeriod: 'Month-to-month, but high base threshold ($165/mo minimum)',
    },
    overview: 'Mangomint is an upscale SaaS platform tailored for medium to large salons and spas (10+ staff). It emphasizes fast, modern workflows and two-way automated client messaging.',
    strengths: [
      'Fast, modern UI without legacy clutter',
      'Smart checkout and virtual waitlist features',
      'Strong automated two-way client texting workflows',
    ],
    weaknesses: [
      'Expensive minimum entry price ($165/mo) makes it unviable for solo and small salons',
      'Two-way SMS carries an additional $30/mo fee',
      'No free freemium plan for onboarding or evaluation',
      'US/Canada centric with limited European localization',
    ],
    darkPatterns: [
      'High Minimum Floor: Refuses to support smaller studios (1-3 chairs) with accessible pricing.',
    ],
    airbookMoatAdvantage: 'AirBook offers the same modern UI speed and aesthetic as Mangomint, while serving solo artists up to multi-location enterprises with a freemium starter tier and global i18n.',
    featureScores: [
      { category: 'Booking Engine UX', airbook: 5, competitor: 4, comparisonNote: 'Both feature fast modern booking; AirBook adds custom color pickers & DAM.' },
      { category: 'Fee Transparency', airbook: 5, competitor: 3, comparisonNote: 'AirBook free tier & transparent pricing vs. Mangomint $165/mo entry floor.' },
      { category: 'White-Label & Domain', airbook: 5, competitor: 4, comparisonNote: 'Both support custom domains; AirBook provides automatic DNS verification.' },
      { category: 'Security & Auth', airbook: 5, competitor: 3, comparisonNote: 'AirBook passkeys vs. standard email/password.' },
      { category: 'POS Terminal Hardware', airbook: 5, competitor: 4, comparisonNote: 'AirBook Stripe Terminal POS vs. standard card terminals.' },
      { category: 'Multi-Language i18n', airbook: 5, competitor: 2, comparisonNote: 'AirBook 4-language support vs. North American English focus.' },
    ],
  },
];

export const AIRBOOK_MOAT_PILLARS = [
  {
    title: 'Zero Marketplace Client Theft (0% Penalty Fee)',
    description: 'Unlike Fresha (20%) and Booksy (50% Boost), AirBook never taxes your newly acquired clients and NEVER recommends competing salons to your customer base.',
    icon: 'ShieldCheckmark24Regular',
    metric: '0% vs 20–50%',
  },
  {
    title: 'True White-Label Custom Domain (CNAME & SSL)',
    description: 'Salons point their own brand domain (e.g. book.bespokesalon.com) with automated wildcard SSL and zero AirBook platform co-branding.',
    icon: 'Globe24Regular',
    metric: '100% White-Label',
  },
  {
    title: 'Tactile Bottom-Sheet Drawer & Passkey Auth',
    description: 'Mobile-first 60fps spring physics with 100% passwordless WebAuthn (Touch ID / Face ID) and zero forced app download walls, boosting conversions 2x.',
    icon: 'Key24Regular',
    metric: '2x Conversion Lift',
  },
  {
    title: 'Smart Gap Sequencing & 10-Min Waitlist',
    description: 'Automated color processing gap scheduling allows stylists to double-book cuts while instant SMS waitlist blasts fill cancellations in under 10 minutes.',
    icon: 'Sparkle24Regular',
    metric: '+35% Daily Chair Yield',
  },
  {
    title: 'Open Stripe Terminal POS & Hardware',
    description: 'Direct pairing with Stripe Terminal WisePad 3 and Tap to Pay on iPhone for tap/chip/PIN payments at direct card-present rates with zero leases.',
    icon: 'Payment24Regular',
    metric: 'Zero Hardware Lock-In',
  },
  {
    title: 'Native 4-Language Internationalization (i18n)',
    description: 'Every client and operator screen is fully localized across English, Spanish, German, and French with circular vector flags for global salon teams.',
    icon: 'Globe24Regular',
    metric: '4 Native Languages',
  },
];

export interface MatrixCategory {
  id: string;
  name: string;
  badge: string;
}

export type FeatureAirBookStatus = 'live' | 'in_progress' | 'planned' | 'missing';

export interface MatrixFeatureItem {
  id: string;
  name: string;
  category: 'pricing' | 'booking' | 'branding' | 'operations' | 'pos' | 'marketing' | 'tech';
  description: string;
  airbook: string;
  airbookStatus: FeatureAirBookStatus;
  roadmapKey?: string; // e.g. 'AIR-102'
  roadmapTitle?: string;
  fresha: string;
  mindbody: string;
  vagaro: string;
  boulevard: string;
  square: string;
  glossgenius: string;
  booksy: string;
  mangomint: string;
  airbookAdvantage: string;
  gapReason?: string;
}

export const MATRIX_CATEGORIES: MatrixCategory[] = [
  { id: 'all', name: 'All Capabilities', badge: '35 Features' },
  { id: 'pricing', name: 'Pricing & Economics', badge: '6 Features' },
  { id: 'booking', name: 'Booking & Client UX', badge: '6 Features' },
  { id: 'branding', name: 'Brand & White-Label', badge: '4 Features' },
  { id: 'operations', name: 'Salon Operations', badge: '5 Features' },
  { id: 'pos', name: 'POS & Hardware', badge: '4 Features' },
  { id: 'marketing', name: 'Marketing & Loyalty', badge: '5 Features' },
  { id: 'tech', name: 'Tech & Compliance', badge: '5 Features' },
];

export const FULL_FEATURE_MATRIX: MatrixFeatureItem[] = [
  // 1. Pricing & Fees
  {
    id: 'f-tax',
    name: 'Marketplace Penalty Tax',
    category: 'pricing',
    description: 'Commission fee levied on clients discovered via marketplace directory.',
    airbook: '0% (Zero Theft)',
    airbookStatus: 'live',
    fresha: '20% + VAT on 1st client',
    mindbody: '0% ($139+ SaaS base)',
    vagaro: '0% (Add-on model)',
    boulevard: '0% ($175+ SaaS floor)',
    square: '0%',
    glossgenius: '0%',
    booksy: 'Up to 50% Booksy Boost',
    mangomint: '0% ($165+ SaaS floor)',
    airbookAdvantage: 'AirBook never taxes newly acquired clients or poaches customer contacts.',
  },
  {
    id: 'f-base',
    name: 'Base Monthly SaaS Subscription',
    category: 'pricing',
    description: 'Fixed entry pricing required to operate calendar and booking engine.',
    airbook: '$0 Free / $29 Pro / $79 Team',
    airbookStatus: 'live',
    fresha: '$0 / mo (Marketplace hook)',
    mindbody: '$139 – $699 / mo',
    vagaro: '$30 / mo + $10/extra staff',
    boulevard: '$175 – $450+ / mo',
    square: '$0 Solo / $29 / $69 / mo',
    glossgenius: '$24 Standard / $48 Gold',
    booksy: '$29.99 / mo + $20/extra',
    mangomint: '$165 / $245 / $375+ / mo',
    airbookAdvantage: 'Freemium solo starter with clear, transparent flat pricing for scaling teams.',
  },
  {
    id: 'f-processing',
    name: 'In-Person Card Processing Rate',
    category: 'pricing',
    description: 'Transaction fee deducted on in-person tap, chip, and card payments.',
    airbook: 'Stripe 2.2% + 15¢ (IC+)',
    airbookStatus: 'live',
    fresha: '2.19% + 20¢ + markups',
    mindbody: '2.75% – 3.5% + monthly gateway',
    vagaro: '2.2% – 2.75% + 15¢',
    boulevard: '2.6% + 10¢ or Custom IC+',
    square: '2.6% + 10¢ flat',
    glossgenius: '2.6% flat rate',
    booksy: '2.49% + 20¢',
    mangomint: '2.45% – 2.6% + 10¢',
    airbookAdvantage: 'Transparent Stripe Connect interchange rates without inflated gateway markups.',
  },
  {
    id: 'f-onboarding',
    name: 'Mandatory Setup & Training Fees',
    category: 'pricing',
    description: 'Upfront fees required to activate software and import customer databases.',
    airbook: '$0 (Instant Self-Serve)',
    airbookStatus: 'live',
    fresha: '$0',
    mindbody: '$300 – $1,000 Setup Fees',
    vagaro: '$0',
    boulevard: 'Mandatory Paid Onboarding',
    square: '$0',
    glossgenius: '$0',
    booksy: '$0',
    mangomint: '$0 – $250 Migration',
    airbookAdvantage: 'Zero setup or onboarding fees. Launch a production storefront in 90 seconds.',
  },
  {
    id: 'f-lockin',
    name: 'Contract Duration & Lock-in',
    category: 'pricing',
    description: 'Required contractual commitment period and cancellation friction.',
    airbook: 'Month-to-month (Zero Lock-in)',
    airbookStatus: 'live',
    fresha: 'No contract (Client lock-in)',
    mindbody: '12–36 Month Locked Annual',
    vagaro: 'Month-to-month',
    boulevard: 'Annual Locked Agreement',
    square: 'Month-to-month',
    glossgenius: 'Month-to-month',
    booksy: 'Month-to-month',
    mangomint: 'Month-to-month',
    airbookAdvantage: '100% freedom to pause or cancel anytime with full CSV/JSON database export.',
  },
  {
    id: 'f-payouts',
    name: 'Payout Speed & Express Transfers',
    category: 'pricing',
    description: 'Time elapsed before card earnings are deposited into operator bank account.',
    airbook: 'Instant / Daily Payouts',
    airbookStatus: 'live',
    fresha: 'Rolling 3-day hold',
    mindbody: 'Weekly / Monthly batch',
    vagaro: '1–3 Business Days',
    boulevard: 'Next-day standard',
    square: 'Instant (1.75%) / Next-day',
    glossgenius: 'Same-day ($) / Next-day',
    booksy: '1–3 Business Days',
    mangomint: 'Next-day standard',
    airbookAdvantage: 'Direct Stripe Connect Express payouts with automated 24-hour transfers.',
  },

  // 2. Booking & UX
  {
    id: 'f-drawer',
    name: 'Mobile Booking Experience',
    category: 'booking',
    description: 'Interaction paradigm on mobile phones and touch viewports.',
    airbook: 'Tactile Bottom-Sheet Drawer',
    airbookStatus: 'live',
    fresha: 'App-Install Wall Modal',
    mindbody: 'Heavy 4s Legacy Iframe',
    vagaro: 'Cluttered Multi-Step Form',
    boulevard: 'Modern Precision Flow',
    square: 'Generic Retail Flow',
    glossgenius: 'Mobile Native Card Flow',
    booksy: 'Directory Search App Wall',
    mangomint: 'Fast Inline Web Widget',
    airbookAdvantage: 'Mobile-first bottom-sheet drawer with 60fps spring physics and zero page reloads.',
  },
  {
    id: 'f-passkeys',
    name: 'Zero-Password Biometric Auth',
    category: 'booking',
    description: 'Authentication standard for salon operators and clients.',
    airbook: '100% WebAuthn / Passkeys',
    airbookStatus: 'live',
    fresha: 'Email & Password',
    mindbody: 'Legacy Password',
    vagaro: 'Password & Security Qs',
    boulevard: 'Password / SSO',
    square: 'Phone OTP & Password',
    glossgenius: 'Phone OTP',
    booksy: 'Phone OTP / Password',
    mangomint: 'Email Link / Password',
    airbookAdvantage: '100% passwordless security via Touch ID, Face ID, and Windows Hello.',
  },
  {
    id: 'f-guest',
    name: 'Guest 1-Tap Booking Checkout',
    category: 'booking',
    description: 'Ability for end clients to book without creating platform passwords.',
    airbook: 'Instant 1-Tap Browser Booking',
    airbookStatus: 'live',
    fresha: 'Requires Fresha Consumer Account',
    mindbody: 'Pushes Mindbody Consumer App',
    vagaro: 'Pushes Vagaro App',
    boulevard: 'Seamless Browser Flow',
    square: 'Browser Flow',
    glossgenius: 'Browser / App Flow',
    booksy: 'Pushes Booksy App Download',
    mangomint: 'Browser Flow',
    airbookAdvantage: 'Zero-friction booking. Clients never face forced app download walls.',
  },
  {
    id: 'f-bundling',
    name: 'Multi-Service Sequencing & Add-ons',
    category: 'booking',
    description: 'Ability to bundle complementary treatments into cohesive appointments with processing gaps.',
    airbook: 'Smart Gap Sequencing (AIR-115)',
    airbookStatus: 'in_progress',
    roadmapKey: 'AIR-115',
    roadmapTitle: 'Smart Service Duration Sequencing & Color Processing Time Gaps',
    fresha: 'Basic Linear Selection',
    mindbody: 'Complex Multi-Booking',
    vagaro: 'Manual Add-on Selection',
    boulevard: 'Precision Multi-Service Stacking',
    square: 'Basic Add-ons',
    glossgenius: 'Linear Multi-Service',
    booksy: 'Linear Service List',
    mangomint: 'Smart Add-on Bundles',
    airbookAdvantage: 'Automated processing time gaps to allow stylists to double-book during color processing.',
    gapReason: 'Boulevard and Mangomint excel at multi-service stacking. AirBook is finalizing split duration blocks in AIR-115.',
  },
  {
    id: 'f-waitlist',
    name: 'Automated Drop-In Waitlist Engine',
    category: 'booking',
    description: 'Instant notification and reservation relay when appointment slots open up.',
    airbook: 'SMS 10-Min Claim (AIR-116)',
    airbookStatus: 'in_progress',
    roadmapKey: 'AIR-116',
    roadmapTitle: 'Drop-In Waitlist Engine with Automated 10-Min Claim Broadcast',
    fresha: 'Manual Staff Notification',
    mindbody: 'Basic Auto-Promote Waitlist',
    vagaro: 'Standard Waitlist ($10/mo)',
    boulevard: 'Smart Automated Waitlist',
    square: 'Basic Waitlist (Plus Plan)',
    glossgenius: 'Manual Waitlist Notes',
    booksy: 'Waitlist Push Notification',
    mangomint: 'Virtual Automated Waitlist',
    airbookAdvantage: 'Broadcasts newly freed slots via SMS with automatic 10-minute first-claim atomic locks.',
    gapReason: 'Automated broadcast when cancellations occur prevents empty salon chairs.',
  },
  {
    id: 'f-selfreschedule',
    name: 'Client Self-Service Rescheduling',
    category: 'booking',
    description: 'Clients reschedule or cancel within salon policy window with late fee protection.',
    airbook: 'Self-Service Shield (AIR-119)',
    airbookStatus: 'in_progress',
    roadmapKey: 'AIR-119',
    roadmapTitle: 'Client Self-Service Reschedule Portal & Late Cancellation Shield',
    fresha: 'Fresha App Reschedule',
    mindbody: 'Consumer App Portal',
    vagaro: 'Vagaro App / Email Link',
    boulevard: 'Self-Service Web Flow',
    square: 'SMS Link Reschedule',
    glossgenius: 'Client Portal',
    booksy: 'Booksy App Reschedule',
    mangomint: 'Self-Service Link',
    airbookAdvantage: 'Passwordless magic link reschedule portal enforcing salon cancellation policy countdowns.',
    gapReason: 'Reduces salon phone interruptions by 70% while guaranteeing no-show fee capture.',
  },

  // 3. Brand & White-Label
  {
    id: 'f-cname',
    name: 'White-Label Custom Domain (CNAME)',
    category: 'branding',
    description: 'Host booking studio on own brand domain (e.g. book.yourbrand.com).',
    airbook: '1-Click Auto SSL CNAME (AIR-103)',
    airbookStatus: 'live',
    roadmapKey: 'AIR-103',
    roadmapTitle: 'Custom Domain White-Label CNAME Automated SSL Engine',
    fresha: 'fresha.com Only (No CNAME)',
    mindbody: 'Expensive Custom App Build',
    vagaro: 'vagaro.com/brand (No CNAME)',
    boulevard: 'Supported on Enterprise',
    square: 'square.site (No CNAME)',
    glossgenius: 'glossgenius.com Subdomain',
    booksy: 'booksy.com Only (No CNAME)',
    mangomint: 'Supported with Custom Setup',
    airbookAdvantage: 'Automated wildcard SSL edge routing with zero AirBook platform branding.',
  },
  {
    id: 'f-isolation',
    name: 'Zero Competitor Cross-Promotion',
    category: 'branding',
    description: 'Guarantee that competitors are never displayed or suggested to clients.',
    airbook: '100% Isolated (Zero Ads)',
    airbookStatus: 'live',
    fresha: 'Cross-Promotes Nearby Salons',
    mindbody: 'Marketplace Poaching',
    vagaro: 'Promotes Competing Salons',
    boulevard: '100% Isolated',
    square: '100% Isolated',
    glossgenius: '100% Isolated',
    booksy: 'Aggressive Boost Hijacking',
    mangomint: '100% Isolated',
    airbookAdvantage: 'Total tenant isolation. We never display competitor directory banners to your clients.',
  },
  {
    id: 'f-colorstudio',
    name: 'AirBook Color Studio & Spectrum',
    category: 'branding',
    description: 'Full custom HSL color physics, dark mode tokens, and theme presets.',
    airbook: '2D HSL Spectrum + Dark Tokens',
    airbookStatus: 'live',
    fresha: 'Fixed Preset Colors',
    mindbody: 'Generic Theme Presets',
    vagaro: 'Basic Color Selection',
    boulevard: 'Custom Luxury Palette',
    square: 'Basic Square Blue Themes',
    glossgenius: 'Preset Card Backgrounds',
    booksy: 'Standard Blue/White Profile',
    mangomint: 'Clean Minimal Theme',
    airbookAdvantage: 'Integrated 2D saturation/brightness spectrum and curated luxury salon DNA palettes.',
  },
  {
    id: 'f-dam',
    name: 'Brand DAM & 3D Vector Media Kit',
    category: 'branding',
    description: 'Integrated digital asset management for logos, cover photos, and lookbooks.',
    airbook: 'High-Res DAM & 3D Icons',
    airbookStatus: 'live',
    fresha: 'Basic Photo Upload',
    mindbody: 'Basic Gallery Upload',
    vagaro: 'Portfolio Photo Gallery',
    boulevard: 'High-Res Media Storage',
    square: 'Basic Image Upload',
    glossgenius: 'Social Lookbook',
    booksy: 'Barber Photo Showcase',
    mangomint: 'Basic Media Library',
    airbookAdvantage: 'High-resolution media management, candid treatment photography, and embed snippets.',
  },

  // 4. Salon Operations
  {
    id: 'f-multiloc',
    name: 'Multi-Location Franchise Switcher',
    category: 'operations',
    description: 'Seamless switching across salon branches with consolidated revenue rollup.',
    airbook: '1-Click Switcher & GMV (AIR-106)',
    airbookStatus: 'live',
    roadmapKey: 'AIR-106',
    roadmapTitle: 'Multi-Branch Location Switcher & Consolidated Analytics',
    fresha: 'Enterprise Location Tier',
    mindbody: 'Complex Enterprise Corporate Hub',
    vagaro: 'Multi-Location ($30/mo extra)',
    boulevard: 'Multi-Location Enterprise',
    square: 'Multi-Location ($45/mo extra)',
    glossgenius: 'Single Location Focus',
    booksy: 'Multi-Location via Biz Pro',
    mangomint: 'Multi-Location Hub ($375+/mo)',
    airbookAdvantage: 'Instant location switching, isolated branch staffing, and unified franchise analytics.',
  },
  {
    id: 'f-commission',
    name: 'Tiered Commission & Chair Rent Split',
    category: 'operations',
    description: 'Flexible compensation models for booth renters, employees, and hybrid staff.',
    airbook: 'Sliding Payroll Scale (AIR-111)',
    airbookStatus: 'missing',
    roadmapKey: 'AIR-111',
    roadmapTitle: 'Tiered Commission Payroll & Booth Rent Split Calculator',
    fresha: 'Standard Commission Reports',
    mindbody: 'Complex Legacy Payroll Rules',
    vagaro: 'Booth Renter Model ($10/mo)',
    boulevard: 'Precision Commission Engine',
    square: 'Basic Commission on Plus Plan',
    glossgenius: 'Simple Commission & Rent',
    booksy: 'Staff Commission Calculator',
    mangomint: 'Two-Way Automated Payroll',
    airbookAdvantage: 'Dynamic service vs. retail product commission tiers and automated booth rent deductions.',
    gapReason: 'Mangomint and Boulevard have automated commission payroll exports. AirBook maps this in AIR-111.',
  },
  {
    id: 'f-waivers',
    name: 'Digital eSign Liability Waivers',
    category: 'operations',
    description: 'Cryptographic digital signature pad for cosmetic and spa intake forms.',
    airbook: 'Cryptographic SHA-256 Pad (AIR-107)',
    airbookStatus: 'live',
    roadmapKey: 'AIR-107',
    roadmapTitle: 'eSign Liability Waiver Signature Pad & Audit Trail',
    fresha: 'External Paper / Form Links',
    mindbody: 'Basic Electronic Waiver',
    vagaro: 'Custom Forms ($10/mo Add-On)',
    boulevard: 'Integrated Digital Forms',
    square: 'Contracts Module (Basic)',
    glossgenius: 'Basic Waiver Template',
    booksy: 'External Consent Forms',
    mangomint: 'Integrated Digital Forms',
    airbookAdvantage: 'Vector canvas signature pad with SHA-256 consent logs and client CRM verification.',
  },
  {
    id: 'f-formulas',
    name: 'Client CRM Formulas & HIPAA Logs',
    category: 'operations',
    description: 'Color formula cards, allergy records, patch tests, and HIPAA audit trails.',
    airbook: 'Color Formulas & HIPAA Logs',
    airbookStatus: 'live',
    fresha: 'Basic Client Notes',
    mindbody: 'SOAP Notes (High Enterprise)',
    vagaro: 'Client Notes & Photos',
    boulevard: 'Custom Technical History',
    square: 'Plain Text Notes',
    glossgenius: 'Formula & Photo Notes',
    booksy: 'Basic Client Notes',
    mangomint: 'Client Timeline & History',
    airbookAdvantage: 'Rich formulation cards, historical before/after attachments, and encrypted audit logs.',
  },
  {
    id: 'f-inventory',
    name: 'Retail Inventory & Barcode SKU Scanner',
    category: 'operations',
    description: 'Barcode scanning, stock depletion, and automated purchase order triggers.',
    airbook: 'Barcode POS & Auto-PO (AIR-110)',
    airbookStatus: 'missing',
    roadmapKey: 'AIR-110',
    roadmapTitle: 'Hardware Barcode SKU Scanner & Automated Purchase Order Engine',
    fresha: 'Basic Product Stock List',
    mindbody: 'Full Retail Inventory System',
    vagaro: 'Online Cart ($10/mo Add-On)',
    boulevard: 'Integrated Retail POS',
    square: 'Advanced Retail Inventory',
    glossgenius: 'Basic Product Inventory',
    booksy: 'Basic Product Sales',
    mangomint: 'Automated Barcode Tracking',
    airbookAdvantage: 'Express USB/Bluetooth barcode scanning, automatic stock decrement upon checkout, and vendor PO generation.',
    gapReason: 'Square and Mindbody offer mature retail barcode inventory. AirBook addresses physical scanning in AIR-110.',
  },

  // 5. POS & Hardware
  {
    id: 'f-terminal',
    name: 'Stripe Terminal In-Person POS',
    category: 'pos',
    description: 'Direct pairing with physical chip/tap/PIN payment terminal readers.',
    airbook: 'WisePad 3 Hardware POS (AIR-102)',
    airbookStatus: 'in_progress',
    roadmapKey: 'AIR-102',
    roadmapTitle: 'Terminal Collect Payment & Reader Display Flow',
    fresha: 'Fresha Card Reader',
    mindbody: 'Proprietary Terminal Hardware',
    vagaro: 'Vagaro EMV Swiper',
    boulevard: 'Boulevard Duo Reader ($400+)',
    square: 'Square Terminal & Stand',
    glossgenius: 'Custom Bluetooth Reader',
    booksy: 'Booksy Card Reader',
    mangomint: 'MagTek & Stripe Readers',
    airbookAdvantage: 'Open Stripe Terminal hardware pairing without proprietary vendor lock-in.',
    gapReason: 'Reader discovery is complete (AIR-101); payment collection & tip settlement is in progress in AIR-102.',
  },
  {
    id: 'f-taptopay',
    name: 'Tap to Pay on iPhone (No Hardware)',
    category: 'pos',
    description: 'Accept contactless card and Apple Pay payments directly on iPhone.',
    airbook: 'Native Apple SDK (AIR-114)',
    airbookStatus: 'missing',
    roadmapKey: 'AIR-114',
    roadmapTitle: 'Direct Tap to Pay on iPhone Contactless Apple SDK Integration',
    fresha: 'Supported in Select Regions',
    mindbody: 'External Reader Required',
    vagaro: 'Vagaro Pay on Phone',
    boulevard: 'External Duo Required',
    square: 'Tap to Pay on iPhone',
    glossgenius: 'Tap to Pay on iPhone',
    booksy: 'External Reader Required',
    mangomint: 'External Reader Required',
    airbookAdvantage: 'Zero-hardware checkout. Turn any iPhone into a payment terminal instantly.',
    gapReason: 'Square and GlossGenius support Tap to Pay on iPhone. AirBook is integrating ProximityReader in AIR-114.',
  },
  {
    id: 'f-splittender',
    name: 'Multi-Tender & Split Bill Checkout',
    category: 'pos',
    description: 'Split payments across cash, card, gift cards, and deposits in 1 transaction.',
    airbook: 'Multi-Tender (Card, Cash, Gift Card)',
    airbookStatus: 'live',
    fresha: 'Split Card/Cash',
    mindbody: 'Multi-Tender Enterprise Split',
    vagaro: 'Split Payment Supported',
    boulevard: 'Luxury Multi-Tender Split',
    square: 'Split Tender Supported',
    glossgenius: 'Single Card or Cash Only',
    booksy: 'Split Card/Cash',
    mangomint: 'Advanced Multi-Tender Split',
    airbookAdvantage: 'Fluid multi-tender checkout with custom deposit deductions and tip calculations.',
  },
  {
    id: 'f-receipts',
    name: 'Thermal & Digital Receipt Engine',
    category: 'pos',
    description: 'Dispatch receipts via SMS, email, or ESC/POS Bluetooth thermal printers.',
    airbook: 'SMS, Email & Thermal (AIR-102)',
    airbookStatus: 'in_progress',
    roadmapKey: 'AIR-102',
    roadmapTitle: 'Terminal Collect Payment & Reader Display Flow',
    fresha: 'Email & SMS Receipts',
    mindbody: 'Thermal & Email Receipts',
    vagaro: 'Thermal, Email & Text',
    boulevard: 'Digital & Thermal Print',
    square: 'Square Thermal & Digital',
    glossgenius: 'Digital SMS/Email Only',
    booksy: 'Digital Receipts',
    mangomint: 'SMS & Thermal Print',
    airbookAdvantage: 'Bespoke HTML/SMS digital receipts paired with ESC/POS standard thermal printers.',
    gapReason: 'Email/SMS receipt sending is implemented; ESC/POS physical thermal print hook is completing in AIR-102.',
  },

  // 6. Marketing & Loyalty
  {
    id: 'f-smsreminders',
    name: 'Automated 2-Way SMS Reminders',
    category: 'marketing',
    description: 'Automated appointment confirmation, reminder, and 2-way client text replies.',
    airbook: '2-Way Twilio Relay (AIR-108)',
    airbookStatus: 'in_progress',
    roadmapKey: 'AIR-108',
    roadmapTitle: 'Automated 2-Way SMS Reminders & Twilio Gateway Relay',
    fresha: 'SMS Credit Surcharge Packs',
    mindbody: 'Paid Add-On (Mindbody Messenger $)',
    vagaro: 'Text Marketing ($10/mo Extra)',
    boulevard: 'Included in Enterprise Plans',
    square: 'Paid SMS Add-on',
    glossgenius: 'Locked in $48/mo Gold',
    booksy: 'SMS Reminder Packages',
    mangomint: 'Two-Way Texting (+$30/mo)',
    airbookAdvantage: 'Automated SMS confirmations and reminders included in core pricing without hidden surcharges.',
    gapReason: 'Twilio 10DLC registration & keyword parsing are in progress in AIR-108.',
  },
  {
    id: 'f-googlereviews',
    name: 'Automated 5-Star Google Reviews',
    category: 'marketing',
    description: 'Post-service review requests with 1-click Google Maps redirect.',
    airbook: 'Reputation Booster (AIR-109)',
    airbookStatus: 'missing',
    roadmapKey: 'AIR-109',
    roadmapTitle: 'Automated 5-Star Google Reviews Booster & Reputation Engine',
    fresha: 'Internal Fresha Reviews Only',
    mindbody: 'External Review Add-on ($)',
    vagaro: 'Vagaro Directory Reviews',
    boulevard: 'Reputation Management Engine',
    square: 'Google Review via Integration',
    glossgenius: 'Review Booster in $48/mo Gold',
    booksy: 'Internal Booksy Reviews Only',
    mangomint: 'Automated Review Requests',
    airbookAdvantage: 'Builds direct organic Google Maps 5-star reputation for the salon, not an aggregator directory.',
    gapReason: 'Boulevard and GlossGenius monetize automated reviews. AirBook is building a native Google Maps booster in AIR-109.',
  },
  {
    id: 'f-memberships',
    name: 'Recurring Memberships & Club Passes',
    category: 'marketing',
    description: 'Automated recurring billing for blow-dry bars, spa clubs, and monthly packages.',
    airbook: 'Stripe Auto-Billing (AIR-112)',
    airbookStatus: 'in_progress',
    roadmapKey: 'AIR-112',
    roadmapTitle: 'Stripe Billing Recurring Memberships & Monthly Credit Sync',
    fresha: 'Basic Voucher Sales',
    mindbody: 'Complex Autopay Contracts',
    vagaro: 'Memberships ($10/mo Add-On)',
    boulevard: 'Luxury Membership Engine',
    square: 'Square Subscriptions Add-on',
    glossgenius: 'Basic Packages',
    booksy: 'Package & Series Sales',
    mangomint: 'Automated Memberships',
    airbookAdvantage: 'Stripe Billing automated recurring payments with instant monthly credit balance sync.',
    gapReason: 'Stripe subscription creation is active; automatic credit deduction at checkout is completing in AIR-112.',
  },
  {
    id: 'f-giftcards',
    name: 'Digital Gift Cards & Promo Codes',
    category: 'marketing',
    description: 'Custom alphanumeric discount codes with min-spend rules and expiration timers.',
    airbook: 'QR Balance Portal (AIR-113)',
    airbookStatus: 'in_progress',
    roadmapKey: 'AIR-113',
    roadmapTitle: 'Digital Gift Card Balance Portal & Point-of-Sale QR Scanner',
    fresha: 'Standard Vouchers',
    mindbody: 'Gift Cards & Promo Codes',
    vagaro: 'Gift Certificates ($10/mo Add-On)',
    boulevard: 'Custom Branded Gift Cards',
    square: 'eGift Cards on Square Directory',
    glossgenius: 'Digital Gift Cards',
    booksy: 'e-Gift Cards',
    mangomint: 'Custom Gift Cards & Promos',
    airbookAdvantage: 'Instant digital gift card issuance with QR code redemption at point of sale.',
    gapReason: 'Issuance is complete; Apple Wallet .pkpass integration is finishing in AIR-113.',
  },
  {
    id: 'f-abandonment',
    name: 'Abandoned Booking Cart Recovery',
    category: 'marketing',
    description: 'Automated SMS / email triggers when a client abandons during date selection.',
    airbook: 'SMS Cart Recovery (AIR-117)',
    airbookStatus: 'missing',
    roadmapKey: 'AIR-117',
    roadmapTitle: 'Abandoned Booking Cart SMS & Email Recovery Sequence',
    fresha: 'None',
    mindbody: 'Marketing Suite ($199+/mo)',
    vagaro: 'None',
    boulevard: 'Precision Recovery Automation',
    square: 'Marketing Suite ($15+/mo)',
    glossgenius: 'None',
    booksy: 'None',
    mangomint: 'Automated Abandoned Triggers',
    airbookAdvantage: 'Recovers up to 18% of abandoned booking intents with friendly automated SMS follow-ups.',
    gapReason: 'Boulevard and Mangomint offer high-converting abandoned cart sequences. AirBook maps this in AIR-117.',
  },

  // 7. Tech & Compliance
  {
    id: 'f-dynamicpricing',
    name: 'Dynamic Yield & Peak-Hour Surge Pricing',
    category: 'tech',
    description: 'Adjust rates based on real-time chair utilization and peak weekend demand.',
    airbook: 'Yield Engine (AIR-118)',
    airbookStatus: 'planned',
    roadmapKey: 'AIR-118',
    roadmapTitle: 'Dynamic Yield & Peak-Hour Surge Pricing Engine',
    fresha: 'None',
    mindbody: 'Dynamic Pricing (Enterprise)',
    vagaro: 'None',
    boulevard: 'Precision Surge Optimization',
    square: 'None',
    glossgenius: 'None',
    booksy: 'None',
    mangomint: 'None',
    airbookAdvantage: 'Transparent demand multipliers that maximize stylist earnings during high-demand Friday/Saturday slots.',
    gapReason: 'Mindbody and Boulevard use yield pricing for enterprise spas. AirBook will implement this in v3.0 (AIR-118).',
  },
  {
    id: 'f-i18n',
    name: '4-Language Internationalization (i18n)',
    category: 'tech',
    description: 'Complete UI localization across English, Spanish, German, and French.',
    airbook: 'Natively EN, ES, DE, FR',
    airbookStatus: 'live',
    fresha: 'Regional Marketplace Portals',
    mindbody: 'Fragmented Legacy Localization',
    vagaro: 'English Centric (US/CA/UK only)',
    boulevard: 'English Only (US/CA only)',
    square: 'Standard Multi-Language Portal',
    glossgenius: 'English Only (US only)',
    booksy: 'Translated Consumer Directory',
    mangomint: 'English Only (US/CA only)',
    airbookAdvantage: 'Zero-compromise internationalization with circular vector flag switchers across 4 languages.',
  },
  {
    id: 'f-offline',
    name: 'Offline-First PWA & Background Sync',
    category: 'tech',
    description: 'Continuous calendar operation during salon internet dropouts and WiFi failures.',
    airbook: 'IndexedDB Caching (AIR-104)',
    airbookStatus: 'live',
    roadmapKey: 'AIR-104',
    roadmapTitle: 'Offline-First Service Worker & PWA Caching Layer',
    fresha: 'Fails / Blank Screen Offline',
    mindbody: 'Fails / Heavy Server Dependency',
    vagaro: 'Fails Offline',
    boulevard: 'Fails Offline',
    square: 'Offline Mode for Payments Only',
    glossgenius: 'Limited Offline Mobile Cache',
    booksy: 'Fails Offline',
    mangomint: 'Fails Offline',
    airbookAdvantage: 'Service Worker and IndexedDB cache keep the calendar interactive even when offline.',
  },
  {
    id: 'f-copilot',
    name: 'Model Context Protocol (MCP) AI Copilot',
    category: 'tech',
    description: 'Autonomous AI voice assistant and natural language appointment booking API.',
    airbook: 'Autonomous Voice & MCP (AIR-105)',
    airbookStatus: 'planned',
    roadmapKey: 'AIR-105',
    roadmapTitle: 'AI Copilot & Natural Language Client Re-Booking Agent',
    fresha: 'None',
    mindbody: 'Legacy Rule Chatbot',
    vagaro: 'None',
    boulevard: 'None',
    square: 'Square AI Text Generation Only',
    glossgenius: 'AI Social Captions Only',
    booksy: 'None',
    mangomint: 'Basic Virtual Assistant',
    airbookAdvantage: 'Model Context Protocol (MCP) endpoint allowing autonomous agents to query availability and book.',
    gapReason: 'Competitors lack true autonomous agentic scheduling. AirBook is building native MCP tools in AIR-105.',
  },
  {
    id: 'f-compliance',
    name: 'HIPAA BAA & GDPR Compliance Security',
    category: 'tech',
    description: 'Encrypted audit telemetry, Business Associate Agreements, and European data sovereignty.',
    airbook: 'Encrypted Audit Trail & BAA',
    airbookStatus: 'live',
    fresha: 'Standard GDPR Only',
    mindbody: 'Enterprise HIPAA (Top Tier)',
    vagaro: 'Standard SSL',
    boulevard: 'SOC2 & HIPAA Compliant',
    square: 'PCI-DSS Level 1 & SOC2',
    glossgenius: 'PCI-DSS Compliant',
    booksy: 'Standard GDPR',
    mangomint: 'HIPAA Ready & Encrypted Cloud',
    airbookAdvantage: 'Built-in HIPAA BAA agreement generator and encrypted administrative audit logging.',
  },
];

export const GAP_ANALYSIS_FEATURES = FULL_FEATURE_MATRIX.filter(
  (f) => f.airbookStatus !== 'live'
);

